# Configuration reference: https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]
base="dark"
font="sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "full"

[server]
headless = true

[browser]
gatherUsageStats = false
